# Generated by Django 4.0.2 on 2025-08-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_guild_description_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
